<?php

namespace QuizzBundle\Repository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeProfil()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p FROM QuizzBundle:Profil p');
        return $query->getResult();
    }
}
