<?php

namespace QuizzBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeQuestion()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT q FROM QuizzBundle:Question q');
        return $query->getResult();
    }

    public function QuestionSuivante($idCat, $idQuest)
{
    $em = $this->getEntityManager();
    $query = $em->createQuery(' SELECT q FROM QuizzBundle:Question q JOIN q.categories c WHERE (c.id = :idCat AND q.id > :idQuest)');
    $query->setParameter('idCat', $idCat);
    $query->setParameter('idQuest', $idQuest);
    $query->setMaxResults(1);

    return $query->getOneOrNullResult();
}

    public function listeQuestionParCategorie($idCategorie)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT q FROM QuizzBundle:Question q LEFT JOIN  q.categories c WHERE c.id = :idCategorie');
        $query->setParameter('idCategorie',$idCategorie);
        return $query->getResult();
    }


    public function PremiereQuestionDeLaCategorie($idCategorie)
    {
        $em =$this->getEntityManager();
        $query = $em->createQuery('SELECT q FROM QuizzBundle:Question q LEFT JOIN q.categories c WHERE c.id = :idCategorie ORDER BY q.id' );
        $query->setParameter('idCategorie',$idCategorie);
        $query->setMaxResults(1);
        return $query->getResult();
    }

    public function DerniereQuestionDeLaCategorie($idCategorie)
    {
        $em =$this->getEntityManager();
        $query = $em->createQuery('SELECT q FROM QuizzBundle:Question q JOIN q.categories c WHERE c.id = :idCategorie ORDER BY q.id DESC');
        $query->setParameter('idCategorie',$idCategorie);
        $query->setMaxResults(1);
        return $query->getResult();
    }

    public function NbDeQuestionDuTest($idTest){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT (q) FROM QuizzBundle:Question q JOIN q.categories c JOIN c.tests t WHERE t.id = :idTest');
        $query->setParameter('idTest', $idTest);
        return $query->getSingleScalarResult();
    }

    public function NbDeQuestionDeLaCategorie($idCategorie){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT (q) FROM QuizzBundle:Question q JOIN q.categories c WHERE c.id = :idCategorie');
        $query->setParameter('idCategorie', $idCategorie);
        return $query->getSingleScalarResult();
    }
}
