<?php

namespace QuizzBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeReponse()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT r FROM QuizzBundle:Reponse r');
        return $query->getResult();
    }

    public function listeReponseParQuestion($idQuestion)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT r FROM QuizzBundle:Reponse r JOIN r.questions q WHERE q.id = :idQuestion');
        $query->setParameter('idQuestion',$idQuestion);
        return $query->getResult();
    }

    public function nbBonneReponseParQuestion($idQuestion)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT r FROM QuizzBundle:Reponse r JOIN r.questions q WHERE q.id =:idQuestion AND  r.estBonne =1' );
        $query->setParameter('idQuestion',$idQuestion);
        return $query->getResult();
    }

    public function EstBonne($idReponse)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT r FROM QuizzBundle:Reponse r WHERE r.id= :idReponse');
        $query->setParameter('idReponse',$idReponse);
        return $query->getResult();
    }
}









