<?php

namespace QuizzBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeTest()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT t FROM QuizzBundle:Test t');
        return $query->getResult();
    }
}
